spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/cachar_complaints}
# For MongoDB Atlas:
# spring.data.mongodb.uri=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}/cachar_complaints?retryWrites=true&w=majority

logging.level.root=WARN
logging.level.com.cachar.complaint=INFO
logging.file.name=/var/log/cachar-complaints/application.log
