spring.data.mongodb.uri=mongodb://ashishunhale1420_db_user:PdkaSguegT36b8A0@ac-jlkvyph-shard-00-00.f0u1sly.mongodb.net:27017,ac-jlkvyph-shard-00-01.f0u1sly.mongodb.net:27017,ac-jlkvyph-shard-00-02.f0u1sly.mongodb.net:27017/cachar_complaints?ssl=true&replicaSet=atlas-n5ljg0-shard-0&authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
logging.level.com.cachar.complaint=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG